<%@ page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<div id="footer">
	<span class="footer">Generated by <a href="http://www.acenonyx.com/">Acenonyx</a> | Copyright &copy; 2013 All Rights Reserved</span> 
</div><!-- end footer --> 

